version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mynewwebstack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-q4vmowo7ieyo"
s3_prefix = "mynewwebstack"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
